# Generated by Django 3.1.5 on 2021-01-18 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(verbose_name='Текст')),
                ('Number', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': ' Описания',
            },
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.CharField(max_length=100, verbose_name='Площадь')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
            ],
            options={
                'verbose_name': 'Королевство',
                'verbose_name_plural': 'Королевства',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('race', models.CharField(max_length=100, verbose_name='Раса')),
                ('sex', models.CharField(max_length=100, verbose_name='Пол')),
                ('Date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Личная информация ',
                'verbose_name_plural': 'Личная информация',
            },
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fame', models.CharField(max_length=100, verbose_name='Известность')),
                ('magic', models.CharField(max_length=100, verbose_name='Магия')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kingdom')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personal')),
            ],
            options={
                'verbose_name': 'Чародей',
                'verbose_name_plural': 'Чародеи',
            },
        ),
        migrations.CreateModel(
            name='WitcherSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Расположение')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
            ],
            options={
                'verbose_name': 'Школа Ведьмаков',
                'verbose_name_plural': 'Школы Ведьмаков',
            },
        ),
        migrations.CreateModel(
            name='Witcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fame', models.CharField(max_length=100, verbose_name='Известность')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personal')),
                ('witcher_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.witcherschool')),
            ],
            options={
                'verbose_name': 'Ведьмак',
                'verbose_name_plural': 'Ведьмаки',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100, verbose_name='Зона')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=100, verbose_name='Способность')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
            ],
            options={
                'verbose_name': 'Чудовище',
                'verbose_name_plural': 'Чудовища',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место контракта')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.monster')),
                ('witcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.witcher')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
